### PR TITLE
Test new NLPModels

### PR DESCRIPTION
**Pull request by abelsiqueira**
Testing with master of NLPModels. If it passes, I will release NLPModels 0.5.0 and discard this.

### CODE REVIEW

**Comment by dpo** [comment]
I enabled TravisCI but I can't seem to log in to Appveyor.

**Comment by dpo** [comment]
Here we go.

**Comment by dpo** [comment]
Do you mean to allow 0.7 to fail?

**Comment by abelsiqueira** [comment]
Yes, JuMP/MPB won't work on 0.7, so this package will need to change to JuMP/MOI first, which is not released yet.

**Comment by dpo** [comment]
Right, ok. Thanks!

**Comment by abelsiqueira** [comment]
Now ready to go.

**Comment by dpo** [comment]
Are we merging this then?

**Comment by abelsiqueira** [comment]
Yes, please

**Comment by dpo** [comment]
Thank you!

**Pull request merged**
